export default {
  Auth: {
    AuthStack: 'AuthStack',
    Login: 'LoginScreen',
    Register: 'RegisterScreen',
    ForgotPassword: 'ForgotPasswordScreen',
    OTPScreen: 'OTPScreen',
    NewPass: 'NewPasswordScreen',
  },
  Main: {
    Home: 'HomeScreen',
    BottonTab: 'BottonTab',
    MainStack: 'MainStack',
    Profile: 'ProfileScreen',
    Settings: 'SettingsScreen',
    Cart: 'CartScreen',
    Favorite: 'Favorite',
    // ProductDetails: 'ProductDetailsScreen',
    Search: 'SearchScreen',
    SearchDetail: 'SearchDetail',
    Orders: 'OrdersScreen',
    Notifications: 'NotificationsScreen',
    ProductDetail: 'ProductDetail',
    Theme : 'Theme',
  },
};
