import {CatchClause} from './../../../node_modules/@babel/types/lib/index-legacy.d';
export default {
  Auth: {
    Welcome: 'WelcomeScreen',
    AuthStack: 'AuthStack',
    Login: 'LoginScreen',
    Register: 'RegisterScreen',
    ForgotPassword: 'ForgotPasswordScreen',
    OTPScreen: 'OTPScreen',
    NewPass: 'NewPasswordScreen',
  },
  Main: {
    Home: 'HomeScreen',
    BottonTab: 'BottonTab',
    MainStack: 'MainStack',
    Profile: 'ProfileScreen',
    Settings: 'SettingsScreen',
    Cart: 'CartScreen',
    Checkout: 'CheckoutScreen',
    Favorite: 'Favorite',
    SearchResult: 'SearchResultScreen',
    Search: 'SearchScreen',
    SearchDetail: 'SearchDetail',
    SearchSplitScreen: 'SearchSplitScreen',
    Orders: 'OrdersScreen',
    Notifications: 'NotificationsScreen',
    ProductDetail: 'ProductDetail',
    Category: 'CategoryScreen',
    Address: 'AddressScreen',
    AddressDetail: 'AddressDetailScreen',
    AddAddress: 'AddAddressScreen',
    OrderDetail: 'OrderDetailScreen',
    Language: 'LangguageScreen',
    Information: 'InformationScreen',
    UpdateInfo: 'UpdateInfo',
    Review: 'ReviewScreen',
    RelatedProductDetail: 'RelatedProductDetail',
    Theme: 'ThemeScreen',
    Voucher: 'VoucherScreen',
    ChangePassword: 'ChangePassword',
    NewPassChange: 'NewPassChange',
    ManageReviewScreen: 'ManageReviewScreen',
    AddReview: 'AddReview',
    ListSearchScreen: 'ListSearchScreen',
    SearchDetailScreen: 'SearchScreennn',
  },
};
